import Link from "next/link";
import { notFound } from "next/navigation";
import { requireFounderPage } from "@/lib/auth";
import { candidateDetail, type EvaluationRow } from "@/lib/data";
import { ROLE_TITLES, type Role } from "@/lib/rubric/types";
import { Badge, ButtonLink, Card, DECISION_LABEL, DECISION_TONE, Notice, ScoreCoverage, StatusBadge, TierBadge, cx, recTone } from "@/components/ui";
import { Tabs } from "@/components/role-tabs";
import { RetryButton } from "@/components/retry-button";

export const dynamic = "force-dynamic";

const NE_REASON: Record<string, string> = {
  interview_only_at_cv_stage: "Interview / work-sample only — must be NE at CV screen",
  model_marked_NE: "Not enough evidence in the CV",
  missing_from_model_output: "Not assessed — treated as NE",
  no_evidence_cited: "No evidence cited — score withheld",
  evidence_not_found_in_cv: "Cited evidence not found verbatim in the CV — score withheld",
  low_score_without_explicit_negative_evidence: "Low score proposed without explicit negative evidence — silence is NE",
  invalid_score: "Invalid score — withheld",
};

export default async function CandidatePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase } = await requireFounderPage();
  const d = await candidateDetail(supabase, id);
  if (!d) notFound();
  const { cand, ident, prof, evalByRole, briefs } = d;
  const applied = cand.applied_role;
  const decision = d.decisions[0];
  const brief = briefs[applied];
  const failed = ["needs_attention", "failed"].includes(cand.status);
  const rubricLabel = (rid: string) => d.rubrics.find((r) => r.id === rid);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <Link href="/" className="text-xs text-faint hover:text-text">← Dashboard</Link>
          <h1 className="mt-1 flex flex-wrap items-center gap-3 text-2xl font-semibold tracking-tight">
            {ident?.full_name ?? cand.original_filename}
            {cand.is_synthetic && <Badge tone="cyan">Synthetic fixture</Badge>}
          </h1>
          <div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-muted">
            <Badge tone="accent">Applied: {applied} · {ROLE_TITLES[applied]}</Badge>
            {cand.applied_rank !== null && <Badge>#{cand.applied_rank} in {applied}</Badge>}
            {cand.in_top5 && <Badge tone="accent">Top five</Badge>}
            <TierBadge tier={cand.rank_tier} />
            <StatusBadge status={cand.status} />
            {decision ? <Badge tone={DECISION_TONE[decision.decision]}>Founder: {DECISION_LABEL[decision.decision]}</Badge> : <Badge>Decision pending</Badge>}
            <span className="font-mono text-xs text-faint">{cand.original_filename}</span>
          </div>
        </div>
        <div className="flex gap-2">
          {failed && <RetryButton candidateId={cand.id} />}
          <ButtonLink href={`/candidates/${cand.id}/decision`}>Decision & email →</ButtonLink>
        </div>
      </div>

      {failed && <Notice tone="danger" title="Processing needs attention">{cand.last_error}</Notice>}
      {cand.possible_duplicate_of && (
        <Notice title="Possible duplicate application">
          Same email address as <Link className="text-accent-strong hover:underline" href={`/candidates/${cand.possible_duplicate_of}`}>another candidate</Link>. Not merged automatically.
        </Notice>
      )}
      {prof?.injection_flags?.length ? (
        <Notice tone="danger" title="This CV contains text that looks like instructions to an AI">
          Flags: {prof.injection_flags.join(", ")}. The CV was treated strictly as data; verify its claims carefully.
        </Notice>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-2">
        {(["PM", "SPM"] as Role[]).map((role) => (
          <RoleSummary key={role} role={role} applied={role === applied} ev={evalByRole[role]} rubric={evalByRole[role] ? rubricLabel(evalByRole[role]!.rubric_version_id) : undefined} />
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <Card title={`Decision brief · ${applied}`} subtitle={brief ? `Generated by ${brief.model} for the top five` : "Briefs are generated for the top five in each role"}>
          {brief ? (
            <div className="space-y-5">
              <ol className="space-y-3">
                {brief.sentences.map((s, i) => (
                  <li key={i} className="flex gap-3 text-[15px] leading-relaxed">
                    <span className="mt-0.5 font-mono text-xs text-accent-strong">{i + 1}</span>
                    <span>{s}</span>
                  </li>
                ))}
              </ol>
              <div>
                <div className="mb-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-faint">Targeted interview questions</div>
                <ul className="space-y-2.5">
                  {brief.interview_questions.map((q, i) => (
                    <li key={i} className="rounded-lg border border-line bg-surface-2 px-3.5 py-3">
                      <div className="flex items-center gap-2">
                        <Badge tone="accent">{q.criterion_code}</Badge>
                        {q.source === "rubric" && <Badge>rubric probe</Badge>}
                      </div>
                      <p className="mt-1.5 text-sm">{q.question}</p>
                      <p className="mt-1 text-xs text-muted">{q.why}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ) : (
            <FallbackQuestions ev={evalByRole[applied]} />
          )}
        </Card>

        <Card title="Data path & privacy" subtitle="What each AI step received for this candidate">
          {prof ? (
            <dl className="space-y-3 text-sm">
              <Row k="Extraction path">{prof.extraction_path === "gemini_ocr" ? "Scanned PDF → Gemini OCR" : prof.extraction_path === "text_layer" ? "PDF text layer (local)" : prof.extraction_path === "docx" ? "DOCX (local)" : "Plain text"}</Row>
              <Row k="Extraction AI saw">{(prof.structured as { extraction_ai_saw?: string })?.extraction_ai_saw ?? "—"}</Row>
              <Row k="Scoring / brief / draft AI saw">Redacted evidence text only (gate re-checked before every call)</Row>
              <Row k="Redactions">
                name ×{prof.redaction_report?.nameReplacements ?? 0} · contacts ×{prof.redaction_report?.contactTokens ?? 0} · personal lines ×{prof.redaction_report?.sensitiveLineReplacements ?? 0} · location ×{prof.redaction_report?.locationReplacements ?? 0}
              </Row>
              <Row k="Residual identifier check">{(prof.redaction_report?.residual ?? []).length ? <span className="text-danger">{prof.redaction_report.residual.join(", ")}</span> : <span className="text-ok">clean</span>}</Row>
              <Row k="Document quality">{prof.document_quality}</Row>
              <Row k="Location signal (for ER only)">{prof.location_signal.replace("_", " ")} · relocation {prof.relocation_signal.replace("_", " ")}</Row>
              <Row k="Restricted fields">
                {ident?.email ? "email ✓" : "email —"} · {ident?.phone ? "phone ✓" : "phone —"} · {ident?.location_text ? "location ✓" : "location —"}
              </Row>
            </dl>
          ) : (
            <p className="text-sm text-muted">Not extracted yet.</p>
          )}
        </Card>
      </div>

      <Card title="Criterion-level evidence" subtitle="Scores only where the CV shows evidence matching an anchor. NE = not enough evidence — never a low score.">
        <Tabs
          initial={applied}
          tabs={(["PM", "SPM"] as Role[]).map((role) => ({
            key: role,
            label: (
              <span>
                {role} {role === applied && <span className="text-accent-strong">· applied</span>}
              </span>
            ),
            content: <CriteriaPanel ev={evalByRole[role]} />,
          }))}
        />
      </Card>

      {prof && (
        <details className="rounded-xl border border-line bg-surface/80">
          <summary className="cursor-pointer px-5 py-3.5 text-[13px] font-semibold">Redacted CV text (exactly what scoring saw)</summary>
          <pre className="max-h-[480px] overflow-auto whitespace-pre-wrap border-t border-line px-5 py-4 font-mono text-xs leading-relaxed text-muted">{prof.redacted_text}</pre>
        </details>
      )}

      {d.jobs.length > 0 && (
        <details className="rounded-xl border border-line bg-surface/80">
          <summary className="cursor-pointer px-5 py-3.5 text-[13px] font-semibold">Processing log</summary>
          <ul className="divide-y divide-line border-t border-line text-xs">
            {d.jobs.map((j) => (
              <li key={j.id} className="flex flex-wrap items-center gap-3 px-5 py-2">
                <span className="font-mono text-faint">#{j.id}</span>
                <span className="w-16">{j.kind}{j.role ? ` ${j.role}` : ""}</span>
                <Badge tone={j.status === "done" ? "ok" : j.status === "failed" ? "danger" : "neutral"}>{j.status}</Badge>
                <span className="text-faint">attempts {j.attempts}</span>
                {j.last_error && <span className="truncate text-danger">{j.last_error}</span>}
              </li>
            ))}
          </ul>
        </details>
      )}
    </div>
  );
}

function Row({ k, children }: { k: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[150px_1fr] gap-3">
      <dt className="text-xs text-faint">{k}</dt>
      <dd className="text-[13px] text-text">{children}</dd>
    </div>
  );
}

function RoleSummary({ role, ev, applied, rubric }: { role: Role; ev?: EvaluationRow; applied: boolean; rubric?: { version_label: string; declared_status: string; is_active: boolean } }) {
  return (
    <div className={cx("rounded-xl border bg-surface/80 p-5 animate-rise", applied ? "border-accent/50 shadow-[0_0_0_1px_#4f7dff22,0_20px_60px_-40px_#4f7dff]" : "border-line")}>
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="font-mono text-sm text-accent-strong">{role}</span>
          <span className="text-sm text-muted">{ROLE_TITLES[role]}</span>
          {applied ? <Badge tone="accent">Applied role · ranked</Badge> : <Badge>Cross-role score · not ranked</Badge>}
        </div>
        {rubric && (
          <span className="font-mono text-[11px] text-faint" title="Rubric version that produced this evaluation">
            rubric v{rubric.version_label}{rubric.is_active ? "" : " (inactive)"}
          </span>
        )}
      </div>
      {ev ? (
        <>
          <div className="mt-4">
            <ScoreCoverage score={ev.score === null ? null : Number(ev.score)} coverage={Number(ev.coverage_pct)} interpretable={ev.recommendation_reasons?.interpretable} />
          </div>
          <div className="mt-3 font-mono text-xs text-muted">{ev.recommendation_reasons?.display}</div>
          <div className="mt-3 flex flex-wrap gap-1.5">
            {(ev.recommendation_reasons?.applicable ?? [ev.recommendation]).map((r) => (
              <Badge key={r} tone={recTone(r)}>{r}</Badge>
            ))}
          </div>
          <ul className="mt-3 space-y-1 text-xs leading-relaxed text-muted">
            {(ev.recommendation_reasons?.reasons ?? []).map((r, i) => (
              <li key={i}>· {r}</li>
            ))}
          </ul>
          <div className="mt-4 grid gap-2 sm:grid-cols-2">
            {ev.essential_requirements.map((e) => (
              <div key={e.code} className="rounded-lg border border-line bg-surface-2 px-3 py-2">
                <div className="flex items-center justify-between gap-2">
                  <span className="font-mono text-[11px] text-faint">{e.code}</span>
                  <Badge tone={e.status === "Confirmed" ? "ok" : e.status === "Unclear" ? "warn" : "danger"}>{e.status}</Badge>
                </div>
                <div className="mt-1 text-xs text-muted">{e.requirement}</div>
                {e.evidence && <div className="mt-1 text-[11px] italic text-faint">“{e.evidence}”</div>}
              </div>
            ))}
          </div>
          <p className="mt-3 text-[11px] text-faint">Essential requirements are status only — never added to the score and never an automatic rejection.</p>
        </>
      ) : (
        <p className="mt-4 text-sm text-muted">Not scored yet for {role}.</p>
      )}
    </div>
  );
}

function CriteriaPanel({ ev }: { ev?: EvaluationRow }) {
  if (!ev) return <p className="text-sm text-muted">Not scored yet.</p>;
  return (
    <div className="space-y-3">
      {ev.criterion_scores.map((c) => (
        <div key={c.code} className="rounded-lg border border-line bg-surface-2/70 p-4">
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-mono text-xs text-accent-strong">{c.code}</span>
            <span className="text-sm font-medium">{c.name}</span>
            <span className="font-mono text-[11px] text-faint">w{c.weight}%</span>
            <Badge>{c.evidenceMode}</Badge>
            <span className="ml-auto flex items-center gap-2">
              {c.status === "scored" ? (
                <>
                  <span className="font-mono text-lg font-semibold">{c.score}</span>
                  <span className="text-xs text-faint">/5</span>
                  <Badge tone={c.confidence === "Medium" ? "accent" : "neutral"}>{c.confidence} confidence</Badge>
                  {c.score !== null && c.score <= 2 && <Badge tone="danger">explicit negative evidence</Badge>}
                </>
              ) : (
                <Badge tone="warn" title={c.neReason ?? ""}>NE · insufficient evidence</Badge>
              )}
            </span>
          </div>
          {c.status === "NE" && c.neReason && <p className="mt-1.5 text-xs text-warn/90">{NE_REASON[c.neReason] ?? c.neReason}</p>}
          {c.reasoning && <p className="mt-2 text-[13px] leading-relaxed text-muted">{c.reasoning}</p>}
          {c.evidence.length > 0 && (
            <ul className="mt-2.5 space-y-1.5">
              {c.evidence.map((e, i) => (
                <li key={i} className="flex gap-2 text-xs">
                  <span className={e.verified ? "text-ok" : "text-danger"} title={e.verified ? "Found verbatim in CV" : "Not found in CV — not counted"}>
                    {e.verified ? "✓" : "✗"}
                  </span>
                  <span className="border-l-2 border-line-strong pl-2 italic text-text/85">“{e.quote}”</span>
                  {e.location && <span className="shrink-0 font-mono text-[10px] text-faint">{e.location}</span>}
                </li>
              ))}
            </ul>
          )}
          {c.reScoreAfterInterview && c.status === "scored" && <p className="mt-2 text-[11px] text-faint">CV-partial: confidence capped; re-score after interview.</p>}
        </div>
      ))}
      {ev.contradictions.length > 0 && (
        <Notice tone="danger" title="Possible contradictions">
          <ul className="space-y-1">
            {ev.contradictions.map((c, i) => (
              <li key={i}>{c.description}</li>
            ))}
          </ul>
        </Notice>
      )}
      {(ev.strongest_evidence || ev.missing_evidence) && (
        <div className="grid gap-3 md:grid-cols-2">
          {ev.strongest_evidence && <Notice tone="ok" title="Strongest role-relevant evidence">{ev.strongest_evidence}</Notice>}
          {ev.missing_evidence && <Notice title="Missing evidence (not a failure)">{ev.missing_evidence}</Notice>}
        </div>
      )}
      {ev.rule_enforcement_log.length > 0 && (
        <details className="rounded-lg border border-line bg-surface-2/50 px-4 py-2.5 text-xs">
          <summary className="cursor-pointer text-muted">Rubric rules applied to the model output ({ev.rule_enforcement_log.length})</summary>
          <ul className="mt-2 space-y-1">
            {ev.rule_enforcement_log.map((l, i) => (
              <li key={i} className="font-mono text-[11px] text-faint">
                {l.code}: {l.change} — {l.rule}
              </li>
            ))}
          </ul>
        </details>
      )}
      <p className="text-[11px] text-faint">Model {ev.model} · weighted total computed in application code from validated criterion scores · evaluated {new Date(ev.created_at).toLocaleString("en-IN")}</p>
    </div>
  );
}

function FallbackQuestions({ ev }: { ev?: EvaluationRow }) {
  if (!ev) return <p className="text-sm text-muted">Scoring not complete yet.</p>;
  const targets = ev.criterion_scores.filter((c) => c.status === "NE" || c.confidence === "Low").slice(0, 3);
  return (
    <div className="space-y-3 text-sm text-muted">
      <p>This candidate is outside the top five, so no AI brief was generated. Criteria to probe if you advance them:</p>
      <ul className="space-y-1.5">
        {targets.map((t) => (
          <li key={t.code} className="flex items-center gap-2">
            <Badge tone="accent">{t.code}</Badge> {t.name} <span className="text-xs text-faint">({t.status === "NE" ? "NE" : "low confidence"})</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
