/**
 * Generates supabase/seed/rubric_seed.sql from rubric/Rubix.txt using the SAME parser and
 * validator the app uses. Run: npm run seed:sql  — then execute the SQL in Supabase (SQL editor).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseRubixText } from "../src/lib/rubric/parse-rubix";
import { validateRubric } from "../src/lib/rubric/validate";
import { buildRubricRows } from "../src/lib/rubric/store";

const src = process.argv[2] ?? "rubric/Rubix.txt";
const out = process.argv[3] ?? "supabase/seed/rubric_seed.sql";
const text = readFileSync(src, "utf8");
const parsed = parseRubixText(text);
const validation = validateRubric(parsed);
if (!validation.ok) {
  console.error(validation.issues.filter((i) => i.level === "error"));
  process.exit(1);
}
const filename = src.split("/").pop()!;
const rows = buildRubricRows({ parsed, validation, sourceText: text, sourceFilename: filename, parseMethod: "rubix_text", importedBy: "seed-script" });

const tag = "$rubric_" + rows.version.source_sha256.slice(0, 8) + "$";
const lit = (v: unknown) => {
  const s = typeof v === "string" ? v : JSON.stringify(v);
  if (s.includes(tag)) throw new Error("dollar tag collision");
  return `${tag}${s}${tag}`;
};
const arr = (a: string[]) => `array[${a.map((x) => lit(x)).join(",")}]::text[]`;

const v = rows.version;
let sql = `-- Generated by scripts/build-rubric-seed.ts from ${filename} (sha256 ${v.source_sha256})\n`;
sql += `-- Idempotent: skips if this exact source is already imported. Activates it if no rubric is active.\nbegin;\n`;
sql += `insert into public.rubric_versions (id, version_label, source_filename, source_text, source_sha256, parse_method, declared_status, parsed, validation, is_active, imported_by)
select '${v.id}', ${lit(v.version_label)}, ${lit(v.source_filename)}, ${lit(v.source_text)}, '${v.source_sha256}', 'rubix_text', ${lit(v.declared_status)}, ${lit(v.parsed)}::jsonb, ${lit(v.validation)}::jsonb, false, 'seed-script'
where not exists (select 1 from public.rubric_versions where source_sha256 = '${v.source_sha256}' and parse_method = 'rubix_text');\n`;
for (const c of rows.criteria) {
  sql += `insert into public.rubric_criteria (rubric_version_id, role, criterion_code, name, weight, evidence_mode, expected_outcome, basis, anchors, acceptable_evidence, interview_probe, hypothesis_refs, historical_supporting_cases, historical_relevant_cases, pattern_confidence, sort_order)
select '${v.id}', '${c.role}', '${c.criterion_code}', ${lit(c.name)}, ${c.weight}, '${c.evidence_mode}', ${lit(c.expected_outcome)}, ${lit(c.basis)}, ${lit(c.anchors)}::jsonb, ${lit(c.acceptable_evidence)}, ${lit(c.interview_probe)}, ${arr(c.hypothesis_refs)}, ${c.historical_supporting_cases}, ${c.historical_relevant_cases}, '${c.pattern_confidence}', ${c.sort_order}
where exists (select 1 from public.rubric_versions where id = '${v.id}') on conflict (rubric_version_id, criterion_code) do nothing;\n`;
}
for (const e of rows.essentials) {
  sql += `insert into public.rubric_essential_requirements (rubric_version_id, role, code, requirement, source, status_rule, essentiality_confirmed, sort_order)
select '${v.id}', '${e.role}', '${e.code}', ${lit(e.requirement)}, ${lit(e.source)}, ${lit(e.status_rule)}, ${e.essentiality_confirmed}, ${e.sort_order}
where exists (select 1 from public.rubric_versions where id = '${v.id}') on conflict (rubric_version_id, code) do nothing;\n`;
}
sql += `update public.rubric_versions set is_active = true, activated_at = now()
 where id = '${v.id}' and not exists (select 1 from public.rubric_versions where is_active);\ncommit;\n`;
writeFileSync(out, sql);
console.log(`wrote ${out} (${sql.length} bytes) — version ${v.version_label}, ${rows.criteria.length} criteria, ${rows.essentials.length} essential requirements, id ${v.id}`);
